version: '3'
services:
  main:
    container_name: rulate_bot_official
    build: .
    restart: always
    network_mode: host
    environment:
      TZ: "Europe/Samara"
      VK_API: ${VK_API}
      VK_API_VERSION: ${VK_API_VERSION}
      VK_GROUP_ID: ${VK_GROUP_ID}
      TG_API: ${TG_API}
      TG_GROUP_ID: ${TG_GROUP_ID}
      TERM: xterm-256color
      COLORTERM: truecolor
    volumes:
      - ./database:/app/database